In [81]:
# Import the Iris Dataset
from sklearn.datasets import load_iris

In [82]:
# Load dataset into a bunch file
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [83]:
# Check out the attributes of the dataset
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [84]:
# Examine the data
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [85]:
# Examine the labels
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [86]:
# Examine our target
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [87]:
# Examine target names
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


### Requirments to work with Scikit-learn
1. Features & Objects must be stored as seperate objects<br>
2. Features & Objects should be numeric<br>
3. Features & Objects should be NumPy Arrays<br>
4. Features & Objects should have specific shapes<br>

In [88]:
# Check to see if feature and response is in NumPy Array
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [89]:
# Check shape of feature
print(iris.data.shape)

(150, 4)


We can see there's 150 observation and 4 features

In [90]:
# Check shape of target
print(iris.target.shape)

(150,)


We have 150 observation, which matches the dimension of our features

In [91]:
# Store feature data in X "Uppercase X because data is a matrix"
X = iris.data

# Store target in y "Lowercase y because target is a vector"
y = iris.target

### Conclusion
* 150 obsevation
* 4 features (sepal length, sepal width, petal length, petal width)
* Classification type (response is categorical)
---

# kNN

### 4 step modeling pattern
1) Import the class

In [92]:
from sklearn.neighbors import KNeighborsClassifier

2) Instantiate the estimator

In [93]:
knn = KNeighborsClassifier(1)

3) Fit the model with the data "model training"
    - This is where the model will learn the relationsip between the features and response

In [94]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

4) Predict the response for new observation

In [96]:
knn.predict([[3,5,4,2]])

array([2])